/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#ffffff",
        "on-background": "#333333",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#1f5fa8",
        "on-primary-fixed": "#1f5fa8",
        "tertiary-fixed": "#dcefdc",
        "on-error": "#ffffff",
        "on-tertiary-container": "#2f7d32",
        "secondary-fixed": "#dce9fb",
        "surface-container-highest": "#e3e9f1",
        "inverse-on-surface": "#ffffff",
        "tertiary-container": "#eaf7ea",
        "surface-variant": "#f5f7fa",
        "secondary": "#1f5fa8",
        "primary-fixed": "#dbeaff",
        "inverse-surface": "#2d2d2d",
        "surface-container": "#f5f7fa",
        "primary": "#2a73cc",
        "surface-tint": "#1f5fa8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f7fa",
        "surface-container-high": "#edf2f8",
        "tertiary-fixed-dim": "#43a047",
        "primary-container": "#1f5fa8",
        "on-surface-variant": "#5f6773",
        "on-primary-fixed-variant": "#1f5fa8",
        "on-secondary-container": "#1f5fa8",
        "on-error-container": "#93000a",
        "background": "#ffffff",
        "on-surface": "#333333",
        "tertiary": "#2e7d32",
        "on-tertiary-fixed": "#1b5e20",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#9fc4f4",
        "on-primary-container": "#eaf2ff",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "outline-variant": "#d7dee8",
        "on-secondary-fixed-variant": "#1f5fa8",
        "primary-fixed-dim": "#c5daf7",
        "secondary-container": "#dce9fb",
        "outline": "#8c96a5",
        "on-tertiary-fixed-variant": "#1b5e20",
        "inverse-primary": "#dbeaff",
        "surface-dim": "#f0f3f7",
        "error": "#ba1a1a",
        "surface": "#ffffff",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
    },
  },
  plugins: [],
}
