/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#f7f9fb",
        "on-background": "#191c1e",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#001f28",
        "on-primary-fixed": "#091d2e",
        "tertiary-fixed": "#89f5e7",
        "on-error": "#ffffff",
        "on-tertiary-container": "#48b8ab",
        "secondary-fixed": "#b7eaff",
        "surface-container-highest": "#e0e3e5",
        "inverse-on-surface": "#eff1f3",
        "tertiary-container": "#00453f",
        "surface-variant": "#e0e3e5",
        "secondary": "#00677f",
        "primary-fixed": "#d1e4fb",
        "inverse-surface": "#2d3133",
        "surface-container": "#eceef0",
        "primary": "#162839",
        "surface-tint": "#4e6073",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface-container-high": "#e6e8ea",
        "tertiary-fixed-dim": "#6bd8cb",
        "primary-container": "#2c3e50",
        "on-surface-variant": "#43474c",
        "on-primary-fixed-variant": "#36485b",
        "on-secondary-container": "#005266",
        "on-error-container": "#93000a",
        "background": "#f7f9fb",
        "on-surface": "#191c1e",
        "tertiary": "#002d28",
        "on-tertiary-fixed": "#00201d",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#4cd6ff",
        "on-primary-container": "#96a9be",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "outline-variant": "#c4c6cd",
        "on-secondary-fixed-variant": "#004e60",
        "primary-fixed-dim": "#b5c8df",
        "secondary-container": "#00ccf9",
        "outline": "#74777d",
        "on-tertiary-fixed-variant": "#005049",
        "inverse-primary": "#b5c8df",
        "surface-dim": "#d8dadc",
        "error": "#ba1a1a",
        "surface": "#f7f9fb",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
    },
  },
  plugins: [],
}
